name: Update develop after main merge

permissions:
  contents: write

on:
  push:
    branches:
    - main

jobs:
  develop_update:
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        fetch-depth: 0

    - name: Disable automatic eol conversion
      run: |
        echo "* -text" > .git/info/attributes

    - name: Checkout develop
      run: |
        git fetch origin main develop
        git checkout develop

    - name: Update develop from main
      run: |
        git config --global user.name "QMK Bot"
        git config --global user.email "hello@qmk.fm"
        git merge origin/main
        git push origin develop
